apiVersion: v1
kind: Pod
metadata:
  name: torch
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  containers:
    - name: torch-pod
      image: 'ghcr.io/stmorse/torch-gen:latest'
      resources:
        requests:
          memory: '4Gi'
          nvidia.com/gpu: '1'
        limits:
          memory: '8Gi'
          nvidia.com/gpu: '1'
      command: ['/bin/sh', '-c', 'sleep infinity']
      volumeMounts:
        - name: home
          mountPath: /home
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse