name: Text Image Build
run-name: Build Text Image
on: 
  push:
    branches:
    - main
    paths:
    - '.github/workflows/text-build.yml'
    - 'text-gen/**'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # shouldn't need this (stmorse is already lowercase) 
    # but keeping because for now I know it sets the right env variable
    - name: Define lowercase repository owner
      id: repo
      run: echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
    - name: Check disk usage
        run: df -h

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./text-gen
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/text-gen:latest
